// AUTO-GENERATED by R. Do not edit by hand.
// Re-run 00_master.R to update.

const BASE = "https://dulal-ramesh.github.io/International_Migration_and_Nepal_Civil_War/Paper/Tables/";

const TABLES = [
  { section: "Summary Tables", subsection: "", title: "Table 1 — Descriptive Statistics", url: BASE + "Tables_Summary/1.Overall_Summary.html" },
  { section: "Summary Tables", subsection: "", title: "Table 2 - Sample Construction", url: BASE + "Tables_Summary/2.Sample_Construction.html" },
  { section: "Summary Tables", subsection: "", title: "Table 3 — Summary by Migration Type", url: BASE + "Tables_Summary/3.Multigroup_Summary.html" },
  { section: "Difference Tables", subsection: "Based on Month of War", title: "Table 4a — High vs Low Conflict (Age 0–17)", url: BASE + "Tables_Summary/4a.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Month of War", title: "Table 4b — High vs Low Conflict (Age 0–5)", url: BASE + "Tables_Summary/4b.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Month of War", title: "Table 4c — High vs Low Conflict (Age 6–12)", url: BASE + "Tables_Summary/4c.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Month of War", title: "Table 4d — High vs Low Conflict (Age 13–17)", url: BASE + "Tables_Summary/4d.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Casualty Number", title: "Table 5a — High vs Low Conflict (Age 0–17)", url: BASE + "Tables_Summary/5a.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Casualty Number", title: "Table 5b — High vs Low Conflict (Age 0–5)", url: BASE + "Tables_Summary/5b.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Casualty Number", title: "Table 5c — High vs Low Conflict (Age 6–12)", url: BASE + "Tables_Summary/5c.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "Based on Casualty Number", title: "Table 5d — High vs Low Conflict (Age 13–17)", url: BASE + "Tables_Summary/5d.Conflict_DiD_Table.html" },
  { section: "Difference Tables", subsection: "DiD Means (Two Measures)", title: "Table 6 — DiD Means by Cohort and Conflict Intensity", url: BASE + "Tables_Summary/6.DiD_Two_Measures.html" },
  { section: "Regression Tables", subsection: "Main DiD Specification", title: "Table 7a — Main DiD: International Migrant", url: BASE + "Tables_Main/7a.DiD_Regression.html" },
  { section: "Regression Tables", subsection: "Main DiD Specification", title: "Table 7b — Main DiD: Currently Abroad", url: BASE + "Tables_Main/7b.DiD_Regression.html" },
  { section: "Regression Tables", subsection: "Main DiD Specification", title: "Table 7c — Main DiD: Return Migrant", url: BASE + "Tables_Main/7c.DiD_Regression.html" },
  { section: "Regression Tables", subsection: "Main DiD Specification", title: "Table 7d — Main DiD: Internal Migration", url: BASE + "Tables_Main/7d.DiD_Regression.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8a — Event Study: International Migrant (Months of War)", url: BASE + "Tables_Main/8a_intl_migrant_months.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8a — Event Study: International Migrant (Casualties)", url: BASE + "Tables_Main/8a_intl_migrant_casualties.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8b — Event Study: Currently Abroad (Months of War)", url: BASE + "Tables_Main/8b_currently_abroad_months.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8b — Event Study: Currently Abroad (Casualties)", url: BASE + "Tables_Main/8b_currently_abroad_casualties.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8c — Event Study: Return Migrant (Months of War)", url: BASE + "Tables_Main/8c_return_migrant_months.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8c — Event Study: Return Migrant (Casualties)", url: BASE + "Tables_Main/8c_return_migrant_casualties.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8d — Event Study: Internal Migration (Months of War)", url: BASE + "Tables_Main/8d_internal_migration_months.Event_Study.html" },
  { section: "Regression Tables", subsection: "Event Study", title: "Table 8d — Event Study: Internal Migration (Casualties)", url: BASE + "Tables_Main/8d_internal_migration_casualties.Event_Study.html" }
];
